<template>
	<div class="px-5">
    <h1>Lorem ipsum dolor sit amet.</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci blanditiis cumque deserunt dolor enim, eos harum incidunt maiores quaerat quidem reiciendis repellendus? Ea explicabo iure magnam nostrum officiis? Blanditiis culpa in possimus tempora voluptatem. A asperiores commodi debitis delectus ea, error expedita explicabo harum illo ipsa iusto labore libero magnam nam neque nostrum obcaecati pariatur quaerat quas quasi quidem ut veniam voluptate! A ab, accusantium aliquam aliquid commodi, consectetur consequatur corporis debitis delectus deleniti doloribus eos et eum illo incidunt laborum laudantium minima nesciunt nihil nobis nostrum officiis placeat praesentium quo quos recusandae reprehenderit saepe similique sint suscipit vel veniam voluptatem, voluptates. Aperiam, dolore ea fugiat iusto numquam provident temporibus! Aspernatur facere illum in, quas ratione reiciendis vel! Accusantium adipisci alias aliquid autem consectetur consequuntur dolor error eveniet id in itaque magni maxime nam nemo officia officiis quam quisquam, quod, reiciendis sapiente similique sint, tempore velit vitae voluptas. Amet esse in laborum odio reiciendis, similique sit unde? Asperiores consequatur eius molestiae nam perferendis placeat porro quos ratione voluptas! Asperiores autem cum deserunt dolore ea et eum fugit illum modi molestias placeat quasi, quidem quos sint veritatis voluptatibus voluptatum. Architecto assumenda commodi dignissimos eaque et magnam maiores molestiae non perferendis repudiandae!</p>
    <h2>Lorem ipsum dolor sit amet.</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci blanditiis cumque deserunt dolor enim, eos harum incidunt maiores quaerat quidem reiciendis repellendus? Ea explicabo iure magnam nostrum officiis? Blanditiis culpa in possimus tempora voluptatem. A asperiores commodi debitis delectus ea, error expedita explicabo harum illo ipsa iusto labore libero magnam nam neque nostrum obcaecati pariatur quaerat quas quasi quidem ut veniam voluptate! A ab, accusantium aliquam aliquid commodi, consectetur consequatur corporis debitis delectus deleniti doloribus eos et eum illo incidunt laborum laudantium minima nesciunt nihil nobis nostrum officiis placeat praesentium quo quos recusandae reprehenderit saepe similique sint suscipit vel veniam voluptatem, voluptates. Aperiam, dolore ea fugiat iusto numquam provident temporibus! Aspernatur facere illum in, quas ratione reiciendis vel! Accusantium adipisci alias aliquid autem consectetur consequuntur dolor error eveniet id in itaque magni maxime nam nemo officia officiis quam quisquam, quod, reiciendis sapiente similique sint, tempore velit vitae voluptas. Amet esse in laborum odio reiciendis, similique sit unde? Asperiores consequatur eius molestiae nam perferendis placeat porro quos ratione voluptas! Asperiores autem cum deserunt dolore ea et eum fugit illum modi molestias placeat quasi, quidem quos sint veritatis voluptatibus voluptatum. Architecto assumenda commodi dignissimos eaque et magnam maiores molestiae non perferendis repudiandae!</p>
    <h2>Lorem ipsum dolor sit amet.</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci blanditiis cumque deserunt dolor enim, eos harum incidunt maiores quaerat quidem reiciendis repellendus? Ea explicabo iure magnam nostrum officiis? Blanditiis culpa in possimus tempora voluptatem. A asperiores commodi debitis delectus ea, error expedita explicabo harum illo ipsa iusto labore libero magnam nam neque nostrum obcaecati pariatur quaerat quas quasi quidem ut veniam voluptate! A ab, accusantium aliquam aliquid commodi, consectetur consequatur corporis debitis delectus deleniti doloribus eos et eum illo incidunt laborum laudantium minima nesciunt nihil nobis nostrum officiis placeat praesentium quo quos recusandae reprehenderit saepe similique sint suscipit vel veniam voluptatem, voluptates. Aperiam, dolore ea fugiat iusto numquam provident temporibus! Aspernatur facere illum in, quas ratione reiciendis vel! Accusantium adipisci alias aliquid autem consectetur consequuntur dolor error eveniet id in itaque magni maxime nam nemo officia officiis quam quisquam, quod, reiciendis sapiente similique sint, tempore velit vitae voluptas. Amet esse in laborum odio reiciendis, similique sit unde? Asperiores consequatur eius molestiae nam perferendis placeat porro quos ratione voluptas! Asperiores autem cum deserunt dolore ea et eum fugit illum modi molestias placeat quasi, quidem quos sint veritatis voluptatibus voluptatum. Architecto assumenda commodi dignissimos eaque et magnam maiores molestiae non perferendis repudiandae!</p>
  </div>
</template>

<script>
export default {
	name: "Index"
}
</script>

<style scoped>

</style>
